# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('elon', models.DecimalField(decimal_places=10, max_digits=19)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=12, unique=True)),
                ('message', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.Marker')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('theme', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
