# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20160406_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='elat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='elon',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
