# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20160406_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='elat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='elon',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
